# Generated by Django 4.1.4 on 2022-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workinfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeepersonal',
            old_name='fName',
            new_name='fname',
        ),
        migrations.RemoveField(
            model_name='employeepersonal',
            name='Age',
        ),
        migrations.AddField(
            model_name='employeepersonal',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
