# Generated by Django 4.1.4 on 2022-12-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workinfo', '0002_rename_fname_employeepersonal_fname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQualify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=50)),
            ],
        ),
    ]
